package pokemon;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import pokemon.Map;
import pokemon.Poke;
import pokemon.Player;
import pokemon.Collection;

class game {
	public static void main(String[] args) {
		
		String input = "";
		Scanner scan = new Scanner(System.in);
		Player user = new Player();
		Map smallMap = new Map();
		Map bigMap = new Map("");
		Map.InitializeHashMaps();
		smallMap.setChunkValues("World1");
		
		Tutorial.tutorial(user, smallMap);
		
		ItemShopDatabase itemshop = new ItemShopDatabase();
		Collection globalPokeDex = new Collection();
		
		String currMap;
		String currSize;
		input = scan.next();
		user.customize();
		System.out.println(itemshop.getItemDescription("PokeBall"));
		spaces();
		//load chunks -> print map -> take input -> repeat
		while(user.execute == 0) {
			spaces();
			currMap = Map.mapGen;
			currSize = Map.mapSize;
			
			//checks for the size of the map, then loads chunks and prints it based off the size.
			//small - 8  : 11; 
			//big   - 24 : 33;
			System.out.println("row: " + Map.userrow + " col: " + Map.usercol);
			if(Map.mapSize.equals("small")) {
				System.out.println("small");
				smallMap.loadChunks(currMap);
				smallMap.printMap(user, currMap, Map.mapSize);
			} else if(Map.mapSize.equals("big")) {
				System.out.println("big");
				bigMap.loadChunks(currMap);
				bigMap.printMap(user, currMap, Map.mapSize);
			}

			//handles the input provided by user, which is processed and influences the chunks and printing of the map (takeInput leads to backbone of game)
			input = scan.next();
			smallMap.takeInput(input, user, currMap, Map.mapSize, itemshop, smallMap);
		}
		scan.close();
	}
	
	
	public static void spaces() {
		System.out.println("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
	}
}

class Tutorial{
	public static void tutorial(Player user, Map map) {
		int term = 0;
		
		Scanner scan = new Scanner(System.in);
		String input = "";
			System.out.println("Welcome to the world of Pokemon!");
			System.out.println("IMPORTANT READ BELOW ");
			System.out.println("\n\n");
			System.out.println("Disclaimers:");
			System.out.println("- The game is currently being worked on and is no where near completed, this is just to showcase the progress");
			System.out.println();
			System.out.println("- The game requires the player to type in a key and then press enter in order to do actions");
			System.out.println();
			System.out.println("- There is currently no system to save progress, which doesn't matter because THERE AREN'T ANY POKEMONS YET LOL");
			System.out.println();
			System.out.println("- Typical 'w a s d' movement with 'c' as the interact/confirm button. Press 'o' to execute the game");
			System.out.println();
			System.out.println("- Have fun walking around for now I guess :)");
			input = scan.next();
		game.spaces();
		String[] positions = new String[3];
		for(int i = 0; i < 3; i++) {
			positions[i] = " ";
		}
		int pos = 0;
		positions[pos] = ">";
		while(term == 0 ) {
			game.spaces();
			System.out.println(positions[0] + " Fizard          " + positions[1] +" Aqualard          " + positions[2] + " Leaflet");
			input = scan.next();
			if(input.equals("a") && pos != 0) {
				positions[pos] = " ";
				pos -= 1;
				positions[pos] = ">";
			} else if(input.equals("d") && pos != 2) {
				positions[pos] = " ";
				pos += 1;
				positions[pos] = ">";
			} else if(input.equals("c")) {
				if(pos == 0) {
					//hp, attack, sp.attack, defense, sp.defense, speed;
					Poke fizard = new Poke("Fizard", "Fire", "NONE",35, 1, 1, 1, 1 ,1, "starter");
					user.addToPokeDex(fizard);
					user.addPokemonToRoster(fizard);
					System.out.println("Fizard has been added to your party!");
				} else if(pos == 1) {
					Poke aqualard = new Poke("Aqualard", "Water", "NONE", 1, 1, 1, 1, 1 ,1, "starter");
					user.addToPokeDex(aqualard);
					user.addPokemonToRoster(aqualard);
					System.out.println("Aqualard has been added to your party!");
				} else if(pos == 2) {
					Poke leaflet = new Poke("Leaftlet", "Grass", "NONE", 1, 1, 1, 1, 1 ,1, "starter");
					user.addToPokeDex(leaflet);
					user.addPokemonToRoster(leaflet);
					System.out.println("Leaflet has been added to your party!");
				}
				
				if(user.collection != null) {
					game.spaces();
					break;
				}
			}
		}
	
	}
	
}



/*
  
  
  
 
 		chunks.get(0).get(0).grid[0]="                  ";chunks.get(0).get(1).grid[0]="                  ";chunks.get(0).get(2).grid[0] ="                  ";chunks.get(0).get(3).grid[0] ="                  ";chunks.get(0).get(4).grid[0] ="                  ";chunks.get(0).get(5).grid[0] ="                  ";chunks.get(0).get(6).grid[0] ="                  ";chunks.get(0).get(7).grid[0] ="                  ";chunks.get(0).get(8).grid[0] ="                  ";chunks.get(0).get(9).grid[0] ="                  ";chunks.get(0).get(10).grid[0] ="                  ";chunks.get(0).get(11).grid[0] ="                  ";chunks.get(0).get(12).grid[0] ="                  ";chunks.get(0).get(13).grid[0] ="                  ";chunks.get(0).get(14).grid[0] ="                  ";chunks.get(0).get(15).grid[0] ="                  ";chunks.get(0).get(16).grid[0] ="                  ";chunks.get(0).get(17).grid[0] ="                  ";chunks.get(0).get(18).grid[0] ="                  ";chunks.get(0).get(19).grid[0] ="                  ";
		chunks.get(0).get(0).grid[1]="                  ";chunks.get(0).get(1).grid[1]="                  ";chunks.get(0).get(2).grid[1] ="                  ";chunks.get(0).get(3).grid[1] ="                  ";chunks.get(0).get(4).grid[1] ="                  ";chunks.get(0).get(5).grid[1] ="                  ";chunks.get(0).get(6).grid[1] ="                  ";chunks.get(0).get(7).grid[1] ="                  ";chunks.get(0).get(8).grid[1] ="                  ";chunks.get(0).get(9).grid[1] ="                  ";chunks.get(0).get(10).grid[1] ="                  ";chunks.get(0).get(11).grid[1] ="                  ";chunks.get(1).get(12).grid[1] ="                  ";chunks.get(0).get(13).grid[1] ="                  ";chunks.get(0).get(14).grid[1] ="                  ";chunks.get(0).get(15).grid[1] ="                  ";chunks.get(0).get(16).grid[1] ="                  ";chunks.get(0).get(17).grid[1] ="                  ";chunks.get(0).get(18).grid[1] ="                  ";chunks.get(0).get(19).grid[1] ="                  ";
		chunks.get(0).get(0).grid[2]="                  ";chunks.get(0).get(1).grid[2]="                  ";chunks.get(0).get(2).grid[2] ="                  ";chunks.get(0).get(3).grid[2] ="                  ";chunks.get(0).get(4).grid[2] ="                  ";chunks.get(0).get(5).grid[2] ="                  ";chunks.get(0).get(6).grid[2] ="                  ";chunks.get(0).get(7).grid[2] ="                  ";chunks.get(0).get(8).grid[2] ="                  ";chunks.get(0).get(9).grid[2] ="                  ";chunks.get(0).get(10).grid[2] ="                  ";chunks.get(0).get(11).grid[2] ="                  ";chunks.get(2).get(12).grid[0] ="                  ";chunks.get(0).get(13).grid[2] ="                  ";chunks.get(0).get(14).grid[2] ="                  ";chunks.get(0).get(15).grid[2] ="                  ";chunks.get(0).get(16).grid[2] ="                  ";chunks.get(0).get(17).grid[2] ="                  ";chunks.get(0).get(18).grid[2] ="                  ";chunks.get(0).get(19).grid[2] ="                  ";
		chunks.get(0).get(0).grid[3]="                  ";chunks.get(0).get(1).grid[3]="                  ";chunks.get(0).get(2).grid[3] ="                  ";chunks.get(0).get(3).grid[3] ="                  ";chunks.get(0).get(4).grid[3] ="                  ";chunks.get(0).get(5).grid[3] ="                  ";chunks.get(0).get(6).grid[3] ="                  ";chunks.get(0).get(7).grid[3] ="                  ";chunks.get(0).get(8).grid[3] ="                  ";chunks.get(0).get(9).grid[3] ="                  ";chunks.get(0).get(10).grid[3] ="                  ";chunks.get(0).get(11).grid[3] ="                  ";chunks.get(3).get(12).grid[0] ="                  ";chunks.get(0).get(13).grid[3] ="                  ";chunks.get(0).get(14).grid[3] ="                  ";chunks.get(0).get(15).grid[3] ="                  ";chunks.get(0).get(16).grid[3] ="                  ";chunks.get(0).get(17).grid[3] ="                  ";chunks.get(0).get(18).grid[3] ="                  ";chunks.get(0).get(19).grid[3] ="                  ";
		chunks.get(0).get(0).grid[4]="                  ";chunks.get(0).get(1).grid[4]="                  ";chunks.get(0).get(2).grid[4] ="                  ";chunks.get(0).get(3).grid[4] ="                  ";chunks.get(0).get(4).grid[4] ="                  ";chunks.get(0).get(5).grid[4] ="                  ";chunks.get(0).get(6).grid[4] ="                  ";chunks.get(0).get(7).grid[4] ="                  ";chunks.get(0).get(8).grid[4] ="                  ";chunks.get(0).get(9).grid[4] ="                  ";chunks.get(0).get(10).grid[4] ="                  ";chunks.get(0).get(11).grid[4] ="                  ";chunks.get(4).get(12).grid[0] ="                  ";chunks.get(0).get(13).grid[4] ="                  ";chunks.get(0).get(14).grid[4] ="                  ";chunks.get(0).get(15).grid[4] ="                  ";chunks.get(0).get(16).grid[4] ="                  ";chunks.get(0).get(17).grid[4] ="                  ";chunks.get(0).get(18).grid[4] ="                  ";chunks.get(0).get(19).grid[4] ="                  ";
		
		chunks.get(1).get(0).grid[0]="                  ";chunks.get(1).get(1).grid[0]="                  ";chunks.get(1).get(2).grid[0] ="                  ";chunks.get(1).get(3).grid[0] ="                  ";chunks.get(1).get(4).grid[0] ="                  ";chunks.get(1).get(5).grid[0] ="                  ";chunks.get(1).get(6).grid[0] ="                  ";chunks.get(1).get(7).grid[0] ="                  ";chunks.get(1).get(8).grid[0] ="                  ";chunks.get(1).get(9).grid[0] ="                  ";chunks.get(1).get(10).grid[0] ="                  ";
		chunks.get(1).get(0).grid[1]="                  ";chunks.get(1).get(1).grid[1]="                  ";chunks.get(1).get(2).grid[1] ="                  ";chunks.get(1).get(3).grid[1] ="                  ";chunks.get(1).get(4).grid[1] ="                  ";chunks.get(1).get(5).grid[1] ="                  ";chunks.get(1).get(6).grid[1] ="                  ";chunks.get(1).get(7).grid[1] ="                  ";chunks.get(1).get(8).grid[1] ="                  ";chunks.get(1).get(9).grid[1] ="                  ";chunks.get(1).get(10).grid[1] ="                  ";
		chunks.get(1).get(0).grid[2]="                  ";chunks.get(1).get(1).grid[2]="                  ";chunks.get(1).get(2).grid[2] ="                  ";chunks.get(1).get(3).grid[2] ="                  ";chunks.get(1).get(4).grid[2] ="                  ";chunks.get(1).get(5).grid[2] ="                  ";chunks.get(1).get(6).grid[2] ="                  ";chunks.get(1).get(7).grid[2] ="                  ";chunks.get(1).get(8).grid[2] ="                  ";chunks.get(1).get(9).grid[2] ="                  ";chunks.get(1).get(10).grid[2] ="                  ";
		chunks.get(1).get(0).grid[3]="                  ";chunks.get(1).get(1).grid[3]="                  ";chunks.get(1).get(2).grid[3] ="                  ";chunks.get(1).get(3).grid[3] ="                  ";chunks.get(1).get(4).grid[3] ="                  ";chunks.get(1).get(5).grid[3] ="                  ";chunks.get(1).get(6).grid[3] ="                  ";chunks.get(1).get(7).grid[3] ="                  ";chunks.get(1).get(8).grid[3] ="                  ";chunks.get(1).get(9).grid[3] ="                  ";chunks.get(1).get(10).grid[3] ="                  ";
		chunks.get(1).get(0).grid[4]="                  ";chunks.get(1).get(1).grid[4]="                  ";chunks.get(1).get(2).grid[4] ="                  ";chunks.get(1).get(3).grid[4] ="                  ";chunks.get(1).get(4).grid[4] ="                  ";chunks.get(1).get(5).grid[4] ="                  ";chunks.get(1).get(6).grid[4] ="                  ";chunks.get(1).get(7).grid[4] ="                  ";chunks.get(1).get(8).grid[4] ="                  ";chunks.get(1).get(9).grid[4] ="                  ";chunks.get(1).get(10).grid[4] ="                  ";
		
		chunks.get(2).get(0).grid[0]="                  ";chunks.get(2).get(1).grid[0]="                  ";chunks.get(2).get(2).grid[0] ="                  ";chunks.get(2).get(3).grid[0] ="                  ";chunks.get(2).get(4).grid[0] ="                  ";chunks.get(2).get(5).grid[0] ="                  ";chunks.get(2).get(6).grid[0] ="                  ";chunks.get(2).get(7).grid[0] ="                  ";chunks.get(2).get(8).grid[0] ="                  ";chunks.get(2).get(9).grid[0] ="                  ";chunks.get(2).get(10).grid[0] ="                  ";
		chunks.get(2).get(0).grid[1]="                  ";chunks.get(2).get(1).grid[1]="                  ";chunks.get(2).get(2).grid[1] ="                  ";chunks.get(2).get(3).grid[1] ="                  ";chunks.get(2).get(4).grid[1] ="                  ";chunks.get(2).get(5).grid[1] ="                  ";chunks.get(2).get(6).grid[1] ="                  ";chunks.get(2).get(7).grid[1] ="                  ";chunks.get(2).get(8).grid[1] ="                  ";chunks.get(2).get(9).grid[1] ="                  ";chunks.get(2).get(10).grid[1] ="                  ";
		chunks.get(2).get(0).grid[2]="                  ";chunks.get(2).get(1).grid[2]="                  ";chunks.get(2).get(2).grid[2] ="                  ";chunks.get(2).get(3).grid[2] ="                  ";chunks.get(2).get(4).grid[2] ="                  ";chunks.get(2).get(5).grid[2] ="                  ";chunks.get(2).get(6).grid[2] ="                  ";chunks.get(2).get(7).grid[2] ="                  ";chunks.get(2).get(8).grid[2] ="                  ";chunks.get(2).get(9).grid[2] ="                  ";chunks.get(2).get(10).grid[2] ="                  ";
		chunks.get(2).get(0).grid[3]="                  ";chunks.get(2).get(1).grid[3]="                  ";chunks.get(2).get(2).grid[3] ="                  ";chunks.get(2).get(3).grid[3] ="                  ";chunks.get(2).get(4).grid[3] ="                  ";chunks.get(2).get(5).grid[3] ="                  ";chunks.get(2).get(6).grid[3] ="                  ";chunks.get(2).get(7).grid[3] ="                  ";chunks.get(2).get(8).grid[3] ="                  ";chunks.get(2).get(9).grid[3] ="                  ";chunks.get(2).get(10).grid[3] ="                  ";
		chunks.get(2).get(0).grid[4]="                  ";chunks.get(2).get(1).grid[4]="                  ";chunks.get(2).get(2).grid[4] ="                  ";chunks.get(2).get(3).grid[4] ="                  ";chunks.get(2).get(4).grid[4] ="                  ";chunks.get(2).get(5).grid[4] ="                  ";chunks.get(2).get(6).grid[4] ="                  ";chunks.get(2).get(7).grid[4] ="                  ";chunks.get(2).get(8).grid[4] ="                  ";chunks.get(2).get(9).grid[4] ="                  ";chunks.get(2).get(10).grid[4] ="                  ";
		
		chunks.get(3).get(0).grid[0]="                  ";chunks.get(3).get(1).grid[0]="                  ";chunks.get(3).get(2).grid[0] ="                  ";chunks.get(3).get(3).grid[0] ="                  ";chunks.get(3).get(4).grid[0] ="                  ";chunks.get(3).get(5).grid[0] ="                  ";chunks.get(3).get(6).grid[0] ="                  ";chunks.get(3).get(7).grid[0] ="                  ";chunks.get(3).get(8).grid[0] ="                  ";chunks.get(3).get(9).grid[0] ="                  ";chunks.get(3).get(10).grid[0] ="                  ";
		chunks.get(3).get(0).grid[1]="                  ";chunks.get(3).get(1).grid[1]="                  ";chunks.get(3).get(2).grid[1] ="                  ";chunks.get(3).get(3).grid[1] ="                  ";chunks.get(3).get(4).grid[1] ="                  ";chunks.get(3).get(5).grid[1] ="                  ";chunks.get(3).get(6).grid[1] ="                  ";chunks.get(3).get(7).grid[1] ="                  ";chunks.get(3).get(8).grid[1] ="                  ";chunks.get(3).get(9).grid[1] ="                  ";chunks.get(3).get(10).grid[1] ="                  ";
		chunks.get(3).get(0).grid[2]="                  ";chunks.get(3).get(1).grid[2]="                  ";chunks.get(3).get(2).grid[2] ="                  ";chunks.get(3).get(3).grid[2] ="                  ";chunks.get(3).get(4).grid[2] ="                  ";chunks.get(3).get(5).grid[2] ="                  ";chunks.get(3).get(6).grid[2] ="                  ";chunks.get(3).get(7).grid[2] ="                  ";chunks.get(3).get(8).grid[2] ="                  ";chunks.get(3).get(9).grid[2] ="                  ";chunks.get(3).get(10).grid[2] ="                  ";
		chunks.get(3).get(0).grid[3]="                  ";chunks.get(3).get(1).grid[3]="                  ";chunks.get(3).get(2).grid[3] ="                  ";chunks.get(3).get(3).grid[3] ="                  ";chunks.get(3).get(4).grid[3] ="                  ";chunks.get(3).get(5).grid[3] ="                  ";chunks.get(3).get(6).grid[3] ="                  ";chunks.get(3).get(7).grid[3] ="                  ";chunks.get(3).get(8).grid[3] ="                  ";chunks.get(3).get(9).grid[3] ="                  ";chunks.get(3).get(10).grid[3] ="                  ";
		chunks.get(3).get(0).grid[4]="                  ";chunks.get(3).get(1).grid[4]="                  ";chunks.get(3).get(2).grid[4] ="                  ";chunks.get(3).get(3).grid[4] ="                  ";chunks.get(3).get(4).grid[4] ="                  ";chunks.get(3).get(5).grid[4] ="                  ";chunks.get(3).get(6).grid[4] ="                  ";chunks.get(3).get(7).grid[4] ="                  ";chunks.get(3).get(8).grid[4] ="                  ";chunks.get(3).get(9).grid[4] ="                  ";chunks.get(3).get(10).grid[4] ="                  ";
		
		chunks.get(4).get(0).grid[0]="                  ";chunks.get(4).get(1).grid[0]="                  ";chunks.get(4).get(2).grid[0] ="                  ";chunks.get(4).get(3).grid[0] ="                  ";chunks.get(4).get(4).grid[0] ="                  ";chunks.get(4).get(5).grid[0] ="                  ";chunks.get(4).get(6).grid[0] ="                  ";chunks.get(4).get(7).grid[0] ="                  ";chunks.get(4).get(8).grid[0] ="                  ";chunks.get(4).get(9).grid[0] ="                  ";chunks.get(4).get(10).grid[0] ="                  ";
		chunks.get(4).get(0).grid[1]="                  ";chunks.get(4).get(1).grid[1]="                  ";chunks.get(4).get(2).grid[1] ="                  ";chunks.get(4).get(3).grid[1] ="                  ";chunks.get(4).get(4).grid[1] ="                  ";chunks.get(4).get(5).grid[1] ="                  ";chunks.get(4).get(6).grid[1] ="                  ";chunks.get(4).get(7).grid[1] ="                  ";chunks.get(4).get(8).grid[1] ="                  ";chunks.get(4).get(9).grid[1] ="                  ";chunks.get(4).get(10).grid[1] ="                  ";
		chunks.get(4).get(0).grid[2]="                  ";chunks.get(4).get(1).grid[2]="                  ";chunks.get(4).get(2).grid[2] ="                  ";chunks.get(4).get(3).grid[2] ="                  ";chunks.get(4).get(4).grid[2] ="                  ";chunks.get(4).get(5).grid[2] ="                  ";chunks.get(4).get(6).grid[2] ="                  ";chunks.get(4).get(7).grid[2] ="                  ";chunks.get(4).get(8).grid[2] ="                  ";chunks.get(4).get(9).grid[2] ="                  ";chunks.get(4).get(10).grid[2] ="                  ";
		chunks.get(4).get(0).grid[3]="                  ";chunks.get(4).get(1).grid[3]="                  ";chunks.get(4).get(2).grid[3] ="                  ";chunks.get(4).get(3).grid[3] ="                  ";chunks.get(4).get(4).grid[3] ="                  ";chunks.get(4).get(5).grid[3] ="                  ";chunks.get(4).get(6).grid[3] ="                  ";chunks.get(4).get(7).grid[3] ="                  ";chunks.get(4).get(8).grid[3] ="                  ";chunks.get(4).get(9).grid[3] ="                  ";chunks.get(4).get(10).grid[3] ="                  ";
		chunks.get(4).get(0).grid[4]="                  ";chunks.get(4).get(1).grid[4]="                  ";chunks.get(4).get(2).grid[4] ="                  ";chunks.get(4).get(3).grid[4] ="                  ";chunks.get(4).get(4).grid[4] ="                  ";chunks.get(4).get(5).grid[4] ="                  ";chunks.get(4).get(6).grid[4] ="                  ";chunks.get(4).get(7).grid[4] ="                  ";chunks.get(4).get(8).grid[4] ="                  ";chunks.get(4).get(9).grid[4] ="                  ";chunks.get(4).get(10).grid[4] ="                  ";
		
		chunks.get(5).get(0).grid[0]="                  ";chunks.get(5).get(1).grid[0]="                  ";chunks.get(5).get(2).grid[0] ="                  ";chunks.get(5).get(3).grid[0] ="                  ";chunks.get(5).get(4).grid[0] ="                  ";chunks.get(5).get(5).grid[0] ="                  ";chunks.get(5).get(6).grid[0] ="                  ";chunks.get(5).get(7).grid[0] ="                  ";chunks.get(5).get(8).grid[0] ="                  ";chunks.get(5).get(9).grid[0] ="                  ";chunks.get(5).get(10).grid[0] ="                  ";
		chunks.get(5).get(0).grid[1]="                  ";chunks.get(5).get(1).grid[1]="                  ";chunks.get(5).get(2).grid[1] ="                  ";chunks.get(5).get(3).grid[1] ="                  ";chunks.get(5).get(4).grid[1] ="                  ";chunks.get(5).get(5).grid[1] ="                  ";chunks.get(5).get(6).grid[1] ="                  ";chunks.get(5).get(7).grid[1] ="                  ";chunks.get(5).get(8).grid[1] ="                  ";chunks.get(5).get(9).grid[1] ="                  ";chunks.get(5).get(10).grid[1] ="                  ";
		chunks.get(5).get(0).grid[2]="                  ";chunks.get(5).get(1).grid[2]="                  ";chunks.get(5).get(2).grid[2] ="                  ";chunks.get(5).get(3).grid[2] ="                  ";chunks.get(5).get(4).grid[2] ="                  ";chunks.get(5).get(5).grid[2] ="                  ";chunks.get(5).get(6).grid[2] ="                  ";chunks.get(5).get(7).grid[2] ="                  ";chunks.get(5).get(8).grid[2] ="                  ";chunks.get(5).get(9).grid[2] ="                  ";chunks.get(5).get(10).grid[2] ="                  ";
		chunks.get(5).get(0).grid[3]="                  ";chunks.get(5).get(1).grid[3]="                  ";chunks.get(5).get(2).grid[3] ="                  ";chunks.get(5).get(3).grid[3] ="                  ";chunks.get(5).get(4).grid[3] ="                  ";chunks.get(5).get(5).grid[3] ="                  ";chunks.get(5).get(6).grid[3] ="                  ";chunks.get(5).get(7).grid[3] ="                  ";chunks.get(5).get(8).grid[3] ="                  ";chunks.get(5).get(9).grid[3] ="                  ";chunks.get(5).get(10).grid[3] ="                  ";
		chunks.get(5).get(0).grid[4]="                  ";chunks.get(5).get(1).grid[4]="                  ";chunks.get(5).get(2).grid[4] ="                  ";chunks.get(5).get(3).grid[4] ="                  ";chunks.get(5).get(4).grid[4] ="                  ";chunks.get(5).get(5).grid[4] ="                  ";chunks.get(5).get(6).grid[4] ="                  ";chunks.get(5).get(7).grid[4] ="                  ";chunks.get(5).get(8).grid[4] ="                  ";chunks.get(5).get(9).grid[4] ="                  ";chunks.get(5).get(10).grid[4] ="                  ";
		
		chunks.get(6).get(0).grid[0]="                  ";chunks.get(6).get(1).grid[0]="                  ";chunks.get(6).get(2).grid[0] ="                  ";chunks.get(6).get(3).grid[0] ="                  ";chunks.get(6).get(4).grid[0] ="                  ";chunks.get(6).get(5).grid[0] ="                  ";chunks.get(6).get(6).grid[0] ="                  ";chunks.get(6).get(7).grid[0] ="                  ";chunks.get(6).get(8).grid[0] ="                  ";chunks.get(6).get(9).grid[0] ="                  ";chunks.get(6).get(10).grid[0] ="                  ";
		chunks.get(6).get(0).grid[1]="                  ";chunks.get(6).get(1).grid[1]="                  ";chunks.get(6).get(2).grid[1] ="                  ";chunks.get(6).get(3).grid[1] ="                  ";chunks.get(6).get(4).grid[1] ="                  ";chunks.get(6).get(5).grid[1] ="                  ";chunks.get(6).get(6).grid[1] ="                  ";chunks.get(6).get(7).grid[1] ="                  ";chunks.get(6).get(8).grid[1] ="                  ";chunks.get(6).get(9).grid[1] ="                  ";chunks.get(6).get(10).grid[1] ="                  ";
		chunks.get(6).get(0).grid[2]="                  ";chunks.get(6).get(1).grid[2]="                  ";chunks.get(6).get(2).grid[2] ="                  ";chunks.get(6).get(3).grid[2] ="                  ";chunks.get(6).get(4).grid[2] ="                  ";chunks.get(6).get(5).grid[2] ="                  ";chunks.get(6).get(6).grid[2] ="                  ";chunks.get(6).get(7).grid[2] ="                  ";chunks.get(6).get(8).grid[2] ="                  ";chunks.get(6).get(9).grid[2] ="                  ";chunks.get(6).get(10).grid[2] ="                  ";
		chunks.get(6).get(0).grid[3]="                  ";chunks.get(6).get(1).grid[3]="                  ";chunks.get(6).get(2).grid[3] ="                  ";chunks.get(6).get(3).grid[3] ="                  ";chunks.get(6).get(4).grid[3] ="                  ";chunks.get(6).get(5).grid[3] ="                  ";chunks.get(6).get(6).grid[3] ="                  ";chunks.get(6).get(7).grid[3] ="                  ";chunks.get(6).get(8).grid[3] ="                  ";chunks.get(6).get(9).grid[3] ="                  ";chunks.get(6).get(10).grid[3] ="                  ";
		chunks.get(6).get(0).grid[4]="                  ";chunks.get(6).get(1).grid[4]="                  ";chunks.get(6).get(2).grid[4] ="                  ";chunks.get(6).get(3).grid[4] ="                  ";chunks.get(6).get(4).grid[4] ="                  ";chunks.get(6).get(5).grid[4] ="                  ";chunks.get(6).get(6).grid[4] ="                  ";chunks.get(6).get(7).grid[4] ="                  ";chunks.get(6).get(8).grid[4] ="                  ";chunks.get(6).get(9).grid[4] ="                  ";chunks.get(6).get(10).grid[4] ="                  ";
		
		chunks.get(7).get(0).grid[0]="                  ";chunks.get(7).get(1).grid[0]="                  ";chunks.get(7).get(2).grid[0] ="                  ";chunks.get(7).get(3).grid[0] ="                  ";chunks.get(7).get(4).grid[0] ="                  ";chunks.get(7).get(5).grid[0] ="                  ";chunks.get(7).get(6).grid[0] ="                  ";chunks.get(7).get(7).grid[0] ="                  ";chunks.get(7).get(8).grid[0] ="                  ";chunks.get(7).get(9).grid[0] ="                  ";chunks.get(7).get(10).grid[0] ="                  ";
		chunks.get(7).get(0).grid[1]="                  ";chunks.get(7).get(1).grid[1]="                  ";chunks.get(7).get(2).grid[1] ="                  ";chunks.get(7).get(3).grid[1] ="                  ";chunks.get(7).get(4).grid[1] ="                  ";chunks.get(7).get(5).grid[1] ="                  ";chunks.get(7).get(6).grid[1] ="                  ";chunks.get(7).get(7).grid[1] ="                  ";chunks.get(7).get(8).grid[1] ="                  ";chunks.get(7).get(9).grid[1] ="                  ";chunks.get(7).get(10).grid[1] ="                  ";
		chunks.get(7).get(0).grid[2]="                  ";chunks.get(7).get(1).grid[2]="                  ";chunks.get(7).get(2).grid[2] ="                  ";chunks.get(7).get(3).grid[2] ="                  ";chunks.get(7).get(4).grid[2] ="                  ";chunks.get(7).get(5).grid[2] ="                  ";chunks.get(7).get(6).grid[2] ="                  ";chunks.get(7).get(7).grid[2] ="                  ";chunks.get(7).get(8).grid[2] ="                  ";chunks.get(7).get(9).grid[2] ="                  ";chunks.get(7).get(10).grid[2] ="                  ";
		chunks.get(7).get(0).grid[3]="                  ";chunks.get(7).get(1).grid[3]="                  ";chunks.get(7).get(2).grid[3] ="                  ";chunks.get(7).get(3).grid[3] ="                  ";chunks.get(7).get(4).grid[3] ="                  ";chunks.get(7).get(5).grid[3] ="                  ";chunks.get(7).get(6).grid[3] ="                  ";chunks.get(7).get(7).grid[3] ="                  ";chunks.get(7).get(8).grid[3] ="                  ";chunks.get(7).get(9).grid[3] ="                  ";chunks.get(7).get(10).grid[3] ="                  ";
		chunks.get(7).get(0).grid[4]="                  ";chunks.get(7).get(1).grid[4]="                  ";chunks.get(7).get(2).grid[4] ="                  ";chunks.get(7).get(3).grid[4] ="                  ";chunks.get(7).get(4).grid[4] ="                  ";chunks.get(7).get(5).grid[4] ="                  ";chunks.get(7).get(6).grid[4] ="                  ";chunks.get(7).get(7).grid[4] ="                  ";chunks.get(7).get(8).grid[4] ="                  ";chunks.get(7).get(9).grid[4] ="                  ";chunks.get(7).get(10).grid[4] ="                  ";

		chunks.get(8).get(0).grid[0]="                  ";chunks.get(8).get(1).grid[0]="                  ";chunks.get(8).get(2).grid[0] ="                  ";chunks.get(8).get(3).grid[0] ="                  ";chunks.get(8).get(4).grid[0] ="                  ";chunks.get(8).get(5).grid[0] ="                  ";chunks.get(8).get(6).grid[0] ="                  ";chunks.get(8).get(7).grid[0] ="                  ";chunks.get(8).get(8).grid[0] ="                  ";chunks.get(8).get(9).grid[0] ="                  ";chunks.get(8).get(10).grid[0] ="                  ";
		chunks.get(8).get(0).grid[1]="                  ";chunks.get(8).get(1).grid[1]="                  ";chunks.get(8).get(2).grid[1] ="                  ";chunks.get(8).get(3).grid[1] ="                  ";chunks.get(8).get(4).grid[1] ="                  ";chunks.get(8).get(5).grid[1] ="                  ";chunks.get(8).get(6).grid[1] ="                  ";chunks.get(8).get(7).grid[1] ="                  ";chunks.get(8).get(8).grid[1] ="                  ";chunks.get(8).get(9).grid[1] ="                  ";chunks.get(8).get(10).grid[1] ="                  ";
		chunks.get(8).get(0).grid[2]="                  ";chunks.get(8).get(1).grid[2]="                  ";chunks.get(8).get(2).grid[2] ="                  ";chunks.get(8).get(3).grid[2] ="                  ";chunks.get(8).get(4).grid[2] ="                  ";chunks.get(8).get(5).grid[2] ="                  ";chunks.get(8).get(6).grid[2] ="                  ";chunks.get(8).get(7).grid[2] ="                  ";chunks.get(8).get(8).grid[2] ="                  ";chunks.get(8).get(9).grid[2] ="                  ";chunks.get(8).get(10).grid[2] ="                  ";
		chunks.get(8).get(0).grid[3]="                  ";chunks.get(8).get(1).grid[3]="                  ";chunks.get(8).get(2).grid[3] ="                  ";chunks.get(8).get(3).grid[3] ="                  ";chunks.get(8).get(4).grid[3] ="                  ";chunks.get(8).get(5).grid[3] ="                  ";chunks.get(8).get(6).grid[3] ="                  ";chunks.get(8).get(7).grid[3] ="                  ";chunks.get(8).get(8).grid[3] ="                  ";chunks.get(8).get(9).grid[3] ="                  ";chunks.get(8).get(10).grid[3] ="                  ";
		chunks.get(8).get(0).grid[4]="                  ";chunks.get(8).get(1).grid[4]="                  ";chunks.get(8).get(2).grid[4] ="                  ";chunks.get(8).get(3).grid[4] ="                  ";chunks.get(8).get(4).grid[4] ="                  ";chunks.get(8).get(5).grid[4] ="                  ";chunks.get(8).get(6).grid[4] ="                  ";chunks.get(8).get(7).grid[4] ="                  ";chunks.get(8).get(8).grid[4] ="                  ";chunks.get(8).get(9).grid[4] ="                  ";chunks.get(8).get(10).grid[4] ="                  ";
		
		chunks.get(9).get(0).grid[0]="                  ";chunks.get(9).get(1).grid[0]="                  ";chunks.get(9).get(2).grid[0] ="                  ";chunks.get(9).get(3).grid[0] ="                  ";chunks.get(9).get(4).grid[0] ="                  ";chunks.get(9).get(5).grid[0] ="                  ";chunks.get(9).get(6).grid[0] ="                  ";chunks.get(9).get(7).grid[0] ="                  ";chunks.get(9).get(8).grid[0] ="                  ";chunks.get(9).get(9).grid[0] ="                  ";chunks.get(9).get(10).grid[0] ="                  ";
		chunks.get(9).get(0).grid[1]="                  ";chunks.get(9).get(1).grid[1]="                  ";chunks.get(9).get(2).grid[1] ="                  ";chunks.get(9).get(3).grid[1] ="                  ";chunks.get(9).get(4).grid[1] ="                  ";chunks.get(9).get(5).grid[1] ="                  ";chunks.get(9).get(6).grid[1] ="                  ";chunks.get(9).get(7).grid[1] ="                  ";chunks.get(9).get(8).grid[1] ="                  ";chunks.get(9).get(9).grid[1] ="                  ";chunks.get(9).get(10).grid[1] ="                  ";
		chunks.get(9).get(0).grid[2]="                  ";chunks.get(9).get(1).grid[2]="                  ";chunks.get(9).get(2).grid[2] ="                  ";chunks.get(9).get(3).grid[2] ="                  ";chunks.get(9).get(4).grid[2] ="                  ";chunks.get(9).get(5).grid[2] ="                  ";chunks.get(9).get(6).grid[2] ="                  ";chunks.get(9).get(7).grid[2] ="                  ";chunks.get(9).get(8).grid[2] ="                  ";chunks.get(9).get(9).grid[2] ="                  ";chunks.get(9).get(10).grid[2] ="                  ";
		chunks.get(9).get(0).grid[3]="                  ";chunks.get(9).get(1).grid[3]="                  ";chunks.get(9).get(2).grid[3] ="                  ";chunks.get(9).get(3).grid[3] ="                  ";chunks.get(9).get(4).grid[3] ="                  ";chunks.get(9).get(5).grid[3] ="                  ";chunks.get(9).get(6).grid[3] ="                  ";chunks.get(9).get(7).grid[3] ="                  ";chunks.get(9).get(8).grid[3] ="                  ";chunks.get(9).get(9).grid[3] ="                  ";chunks.get(9).get(10).grid[3] ="                  ";
		chunks.get(9).get(0).grid[4]="                  ";chunks.get(9).get(1).grid[4]="                  ";chunks.get(9).get(2).grid[4] ="                  ";chunks.get(9).get(3).grid[4] ="                  ";chunks.get(9).get(4).grid[4] ="                  ";chunks.get(9).get(5).grid[4] ="                  ";chunks.get(9).get(6).grid[4] ="                  ";chunks.get(9).get(7).grid[4] ="                  ";chunks.get(9).get(8).grid[4] ="                  ";chunks.get(9).get(9).grid[4] ="                  ";chunks.get(9).get(10).grid[4] ="                  ";
		
		chunks.get(10).get(0).grid[0]="                  ";chunks.get(10).get(1).grid[0]="                  ";chunks.get(10).get(2).grid[0] ="                  ";chunks.get(10).get(3).grid[0] ="                  ";chunks.get(10).get(4).grid[0] ="                  ";chunks.get(10).get(5).grid[0] ="                  ";chunks.get(10).get(6).grid[0] ="                  ";chunks.get(10).get(7).grid[0] ="                  ";chunks.get(10).get(8).grid[0] ="                  ";chunks.get(10).get(9).grid[0] ="                  ";chunks.get(10).get(10).grid[0] ="                  ";
		chunks.get(10).get(0).grid[1]="                  ";chunks.get(10).get(1).grid[1]="                  ";chunks.get(10).get(2).grid[1] ="                  ";chunks.get(10).get(3).grid[1] ="                  ";chunks.get(10).get(4).grid[1] ="                  ";chunks.get(10).get(5).grid[1] ="                  ";chunks.get(10).get(6).grid[1] ="                  ";chunks.get(10).get(7).grid[1] ="                  ";chunks.get(10).get(8).grid[1] ="                  ";chunks.get(10).get(9).grid[1] ="                  ";chunks.get(10).get(10).grid[1] ="                  ";
		chunks.get(10).get(0).grid[2]="                  ";chunks.get(10).get(1).grid[2]="                  ";chunks.get(10).get(2).grid[2] ="                  ";chunks.get(10).get(3).grid[2] ="                  ";chunks.get(10).get(4).grid[2] ="                  ";chunks.get(10).get(5).grid[2] ="                  ";chunks.get(10).get(6).grid[2] ="                  ";chunks.get(10).get(7).grid[2] ="                  ";chunks.get(10).get(8).grid[2] ="                  ";chunks.get(10).get(9).grid[2] ="                  ";chunks.get(10).get(10).grid[2] ="                  ";
		chunks.get(10).get(0).grid[3]="                  ";chunks.get(10).get(1).grid[3]="                  ";chunks.get(10).get(2).grid[3] ="                  ";chunks.get(10).get(3).grid[3] ="                  ";chunks.get(10).get(4).grid[3] ="                  ";chunks.get(10).get(5).grid[3] ="                  ";chunks.get(10).get(6).grid[3] ="                  ";chunks.get(10).get(7).grid[3] ="                  ";chunks.get(10).get(8).grid[3] ="                  ";chunks.get(10).get(9).grid[3] ="                  ";chunks.get(10).get(10).grid[3] ="                  ";
		chunks.get(10).get(0).grid[4]="                  ";chunks.get(10).get(1).grid[4]="                  ";chunks.get(10).get(2).grid[4] ="                  ";chunks.get(10).get(3).grid[4] ="                  ";chunks.get(10).get(4).grid[4] ="                  ";chunks.get(10).get(5).grid[4] ="                  ";chunks.get(10).get(6).grid[4] ="                  ";chunks.get(10).get(7).grid[4] ="                  ";chunks.get(10).get(8).grid[4] ="                  ";chunks.get(10).get(9).grid[4] ="                  ";chunks.get(10).get(10).grid[4] ="                  ";
		
		chunks.get(11).get(0).grid[0]="                  ";chunks.get(11).get(1).grid[0]="                  ";chunks.get(11).get(2).grid[0] ="                  ";chunks.get(11).get(3).grid[0] ="                  ";chunks.get(11).get(4).grid[0] ="                  ";chunks.get(11).get(5).grid[0] ="                  ";chunks.get(11).get(6).grid[0] ="                  ";chunks.get(11).get(7).grid[0] ="                  ";chunks.get(11).get(8).grid[0] ="                  ";chunks.get(11).get(9).grid[0] ="                  ";chunks.get(11).get(10).grid[0] ="                  ";
		chunks.get(11).get(0).grid[1]="                  ";chunks.get(11).get(1).grid[1]="                  ";chunks.get(11).get(2).grid[1] ="                  ";chunks.get(11).get(3).grid[1] ="                  ";chunks.get(11).get(4).grid[1] ="                  ";chunks.get(11).get(5).grid[1] ="                  ";chunks.get(11).get(6).grid[1] ="                  ";chunks.get(11).get(7).grid[1] ="                  ";chunks.get(11).get(8).grid[1] ="                  ";chunks.get(11).get(9).grid[1] ="                  ";chunks.get(11).get(10).grid[1] ="                  ";
		chunks.get(11).get(0).grid[2]="                  ";chunks.get(11).get(1).grid[2]="                  ";chunks.get(11).get(2).grid[2] ="                  ";chunks.get(11).get(3).grid[2] ="                  ";chunks.get(11).get(4).grid[2] ="                  ";chunks.get(11).get(5).grid[2] ="                  ";chunks.get(11).get(6).grid[2] ="                  ";chunks.get(11).get(7).grid[2] ="                  ";chunks.get(11).get(8).grid[2] ="                  ";chunks.get(11).get(9).grid[2] ="                  ";chunks.get(11).get(10).grid[2] ="                  ";
		chunks.get(11).get(0).grid[3]="                  ";chunks.get(11).get(1).grid[3]="                  ";chunks.get(11).get(2).grid[3] ="                  ";chunks.get(11).get(3).grid[3] ="                  ";chunks.get(11).get(4).grid[3] ="                  ";chunks.get(11).get(5).grid[3] ="                  ";chunks.get(11).get(6).grid[3] ="                  ";chunks.get(11).get(7).grid[3] ="                  ";chunks.get(11).get(8).grid[3] ="                  ";chunks.get(11).get(9).grid[3] ="                  ";chunks.get(11).get(10).grid[3] ="                  ";
		chunks.get(11).get(0).grid[4]="                  ";chunks.get(11).get(1).grid[4]="                  ";chunks.get(11).get(2).grid[4] ="                  ";chunks.get(11).get(3).grid[4] ="                  ";chunks.get(11).get(4).grid[4] ="                  ";chunks.get(11).get(5).grid[4] ="                  ";chunks.get(11).get(6).grid[4] ="                  ";chunks.get(11).get(7).grid[4] ="                  ";chunks.get(11).get(8).grid[4] ="                  ";chunks.get(11).get(9).grid[4] ="                  ";chunks.get(11).get(10).grid[4] ="                  ";
		
		chunks.get(12).get(0).grid[0]="                  ";chunks.get(12).get(1).grid[0]="                  ";chunks.get(12).get(2).grid[0] ="                  ";chunks.get(12).get(3).grid[0] ="                  ";chunks.get(12).get(4).grid[0] ="                  ";chunks.get(12).get(5).grid[0] ="                  ";chunks.get(12).get(6).grid[0] ="                  ";chunks.get(12).get(7).grid[0] ="                  ";chunks.get(12).get(8).grid[0] ="                  ";chunks.get(12).get(9).grid[0] ="                  ";chunks.get(12).get(10).grid[0] ="                  ";
		chunks.get(12).get(0).grid[1]="                  ";chunks.get(12).get(1).grid[1]="                  ";chunks.get(12).get(2).grid[1] ="                  ";chunks.get(12).get(3).grid[1] ="                  ";chunks.get(12).get(4).grid[1] ="                  ";chunks.get(12).get(5).grid[1] ="                  ";chunks.get(12).get(6).grid[1] ="                  ";chunks.get(12).get(7).grid[1] ="                  ";chunks.get(12).get(8).grid[1] ="                  ";chunks.get(12).get(9).grid[1] ="                  ";chunks.get(12).get(10).grid[1] ="                  ";
		chunks.get(12).get(0).grid[2]="                  ";chunks.get(12).get(1).grid[2]="                  ";chunks.get(12).get(2).grid[2] ="                  ";chunks.get(12).get(3).grid[2] ="                  ";chunks.get(12).get(4).grid[2] ="                  ";chunks.get(12).get(5).grid[2] ="                  ";chunks.get(12).get(6).grid[2] ="                  ";chunks.get(12).get(7).grid[2] ="                  ";chunks.get(12).get(8).grid[2] ="                  ";chunks.get(12).get(9).grid[2] ="                  ";chunks.get(12).get(10).grid[2] ="                  ";
		chunks.get(12).get(0).grid[3]="                  ";chunks.get(12).get(1).grid[3]="                  ";chunks.get(12).get(2).grid[3] ="                  ";chunks.get(12).get(3).grid[3] ="                  ";chunks.get(12).get(4).grid[3] ="                  ";chunks.get(12).get(5).grid[3] ="                  ";chunks.get(12).get(6).grid[3] ="                  ";chunks.get(12).get(7).grid[3] ="                  ";chunks.get(12).get(8).grid[3] ="                  ";chunks.get(12).get(9).grid[3] ="                  ";chunks.get(12).get(10).grid[3] ="                  ";
		chunks.get(12).get(0).grid[4]="                  ";chunks.get(12).get(1).grid[4]="                  ";chunks.get(12).get(2).grid[4] ="                  ";chunks.get(12).get(3).grid[4] ="                  ";chunks.get(12).get(4).grid[4] ="                  ";chunks.get(12).get(5).grid[4] ="                  ";chunks.get(12).get(6).grid[4] ="                  ";chunks.get(12).get(7).grid[4] ="                  ";chunks.get(12).get(8).grid[4] ="                  ";chunks.get(12).get(9).grid[4] ="                  ";chunks.get(12).get(10).grid[4] ="                  ";
		
		chunks.get(13).get(0).grid[0]="                  ";chunks.get(13).get(1).grid[0]="                  ";chunks.get(13).get(2).grid[0] ="                  ";chunks.get(13).get(3).grid[0] ="                  ";chunks.get(13).get(4).grid[0] ="                  ";chunks.get(13).get(5).grid[0] ="                  ";chunks.get(13).get(6).grid[0] ="                  ";chunks.get(13).get(7).grid[0] ="                  ";chunks.get(13).get(8).grid[0] ="                  ";chunks.get(13).get(9).grid[0] ="                  ";chunks.get(13).get(10).grid[0] ="                  ";
		chunks.get(13).get(0).grid[1]="                  ";chunks.get(13).get(1).grid[1]="                  ";chunks.get(13).get(2).grid[1] ="                  ";chunks.get(13).get(3).grid[1] ="                  ";chunks.get(13).get(4).grid[1] ="                  ";chunks.get(13).get(5).grid[1] ="                  ";chunks.get(13).get(6).grid[1] ="                  ";chunks.get(13).get(7).grid[1] ="                  ";chunks.get(13).get(8).grid[1] ="                  ";chunks.get(13).get(9).grid[1] ="                  ";chunks.get(13).get(10).grid[1] ="                  ";
		chunks.get(13).get(0).grid[2]="                  ";chunks.get(13).get(1).grid[2]="                  ";chunks.get(13).get(2).grid[2] ="                  ";chunks.get(13).get(3).grid[2] ="                  ";chunks.get(13).get(4).grid[2] ="                  ";chunks.get(13).get(5).grid[2] ="                  ";chunks.get(13).get(6).grid[2] ="                  ";chunks.get(13).get(7).grid[2] ="                  ";chunks.get(13).get(8).grid[2] ="                  ";chunks.get(13).get(9).grid[2] ="                  ";chunks.get(13).get(10).grid[2] ="                  ";
		chunks.get(13).get(0).grid[3]="                  ";chunks.get(13).get(1).grid[3]="                  ";chunks.get(13).get(2).grid[3] ="                  ";chunks.get(13).get(3).grid[3] ="                  ";chunks.get(13).get(4).grid[3] ="                  ";chunks.get(13).get(5).grid[3] ="                  ";chunks.get(13).get(6).grid[3] ="                  ";chunks.get(13).get(7).grid[3] ="                  ";chunks.get(13).get(8).grid[3] ="                  ";chunks.get(13).get(9).grid[3] ="                  ";chunks.get(13).get(10).grid[3] ="                  ";
		chunks.get(13).get(0).grid[4]="                  ";chunks.get(13).get(1).grid[4]="                  ";chunks.get(13).get(2).grid[4] ="                  ";chunks.get(13).get(3).grid[4] ="                  ";chunks.get(13).get(4).grid[4] ="                  ";chunks.get(13).get(5).grid[4] ="                  ";chunks.get(13).get(6).grid[4] ="                  ";chunks.get(13).get(7).grid[4] ="                  ";chunks.get(13).get(8).grid[4] ="                  ";chunks.get(13).get(9).grid[4] ="                  ";chunks.get(13).get(10).grid[4] ="                  ";
		
		chunks.get(14).get(0).grid[0]="                  ";chunks.get(14).get(1).grid[0]="                  ";chunks.get(14).get(2).grid[0] ="                  ";chunks.get(14).get(3).grid[0] ="                  ";chunks.get(14).get(4).grid[0] ="                  ";chunks.get(14).get(5).grid[0] ="                  ";chunks.get(14).get(6).grid[0] ="                  ";chunks.get(14).get(7).grid[0] ="                  ";chunks.get(14).get(8).grid[0] ="                  ";chunks.get(14).get(9).grid[0] ="                  ";chunks.get(14).get(10).grid[0] ="                  ";
		chunks.get(14).get(0).grid[1]="                  ";chunks.get(14).get(1).grid[1]="                  ";chunks.get(14).get(2).grid[1] ="                  ";chunks.get(14).get(3).grid[1] ="                  ";chunks.get(14).get(4).grid[1] ="                  ";chunks.get(14).get(5).grid[1] ="                  ";chunks.get(14).get(6).grid[1] ="                  ";chunks.get(14).get(7).grid[1] ="                  ";chunks.get(14).get(8).grid[1] ="                  ";chunks.get(14).get(9).grid[1] ="                  ";chunks.get(14).get(10).grid[1] ="                  ";
		chunks.get(14).get(0).grid[2]="                  ";chunks.get(14).get(1).grid[2]="                  ";chunks.get(14).get(2).grid[2] ="                  ";chunks.get(14).get(3).grid[2] ="                  ";chunks.get(14).get(4).grid[2] ="                  ";chunks.get(14).get(5).grid[2] ="                  ";chunks.get(14).get(6).grid[2] ="                  ";chunks.get(14).get(7).grid[2] ="                  ";chunks.get(14).get(8).grid[2] ="                  ";chunks.get(14).get(9).grid[2] ="                  ";chunks.get(14).get(10).grid[2] ="                  ";
		chunks.get(14).get(0).grid[3]="                  ";chunks.get(14).get(1).grid[3]="                  ";chunks.get(14).get(2).grid[3] ="                  ";chunks.get(14).get(3).grid[3] ="                  ";chunks.get(14).get(4).grid[3] ="                  ";chunks.get(14).get(5).grid[3] ="                  ";chunks.get(14).get(6).grid[3] ="                  ";chunks.get(14).get(7).grid[3] ="                  ";chunks.get(14).get(8).grid[3] ="                  ";chunks.get(14).get(9).grid[3] ="                  ";chunks.get(14).get(10).grid[3] ="                  ";
		chunks.get(14).get(0).grid[4]="                  ";chunks.get(14).get(1).grid[4]="                  ";chunks.get(14).get(2).grid[4] ="                  ";chunks.get(14).get(3).grid[4] ="                  ";chunks.get(14).get(4).grid[4] ="                  ";chunks.get(14).get(5).grid[4] ="                  ";chunks.get(14).get(6).grid[4] ="                  ";chunks.get(14).get(7).grid[4] ="                  ";chunks.get(14).get(8).grid[4] ="                  ";chunks.get(14).get(9).grid[4] ="                  ";chunks.get(14).get(10).grid[4] ="                  ";
		
		chunks.get(15).get(0).grid[0]="                  ";chunks.get(15).get(1).grid[0]="                  ";chunks.get(15).get(2).grid[0] ="                  ";chunks.get(15).get(3).grid[0] ="                  ";chunks.get(15).get(4).grid[0] ="                  ";chunks.get(15).get(5).grid[0] ="                  ";chunks.get(15).get(6).grid[0] ="                  ";chunks.get(15).get(7).grid[0] ="                  ";chunks.get(15).get(8).grid[0] ="                  ";chunks.get(15).get(9).grid[0] ="                  ";chunks.get(15).get(10).grid[0] ="                  ";
		chunks.get(15).get(0).grid[1]="                  ";chunks.get(15).get(1).grid[1]="                  ";chunks.get(15).get(2).grid[1] ="                  ";chunks.get(15).get(3).grid[1] ="                  ";chunks.get(15).get(4).grid[1] ="                  ";chunks.get(15).get(5).grid[1] ="                  ";chunks.get(15).get(6).grid[1] ="                  ";chunks.get(15).get(7).grid[1] ="                  ";chunks.get(15).get(8).grid[1] ="                  ";chunks.get(15).get(9).grid[1] ="                  ";chunks.get(15).get(10).grid[1] ="                  ";
		chunks.get(15).get(0).grid[2]="                  ";chunks.get(15).get(1).grid[2]="                  ";chunks.get(15).get(2).grid[2] ="                  ";chunks.get(15).get(3).grid[2] ="                  ";chunks.get(15).get(4).grid[2] ="                  ";chunks.get(15).get(5).grid[2] ="                  ";chunks.get(15).get(6).grid[2] ="                  ";chunks.get(15).get(7).grid[2] ="                  ";chunks.get(15).get(8).grid[2] ="                  ";chunks.get(15).get(9).grid[2] ="                  ";chunks.get(15).get(10).grid[2] ="                  ";
		chunks.get(15).get(0).grid[3]="                  ";chunks.get(15).get(1).grid[3]="                  ";chunks.get(15).get(2).grid[3] ="                  ";chunks.get(15).get(3).grid[3] ="                  ";chunks.get(15).get(4).grid[3] ="                  ";chunks.get(15).get(5).grid[3] ="                  ";chunks.get(15).get(6).grid[3] ="                  ";chunks.get(15).get(7).grid[3] ="                  ";chunks.get(15).get(8).grid[3] ="                  ";chunks.get(15).get(9).grid[3] ="                  ";chunks.get(15).get(10).grid[3] ="                  ";
		chunks.get(15).get(0).grid[4]="                  ";chunks.get(15).get(1).grid[4]="                  ";chunks.get(15).get(2).grid[4] ="                  ";chunks.get(15).get(3).grid[4] ="                  ";chunks.get(15).get(4).grid[4] ="                  ";chunks.get(15).get(5).grid[4] ="                  ";chunks.get(15).get(6).grid[4] ="                  ";chunks.get(15).get(7).grid[4] ="                  ";chunks.get(15).get(8).grid[4] ="                  ";chunks.get(15).get(9).grid[4] ="                  ";chunks.get(15).get(10).grid[4] ="                  ";
		
		chunks.get(16).get(0).grid[0]="                  ";chunks.get(16).get(1).grid[0]="                  ";chunks.get(16).get(2).grid[0] ="                  ";chunks.get(16).get(3).grid[0] ="                  ";chunks.get(16).get(4).grid[0] ="                  ";chunks.get(16).get(5).grid[0] ="                  ";chunks.get(16).get(6).grid[0] ="                  ";chunks.get(16).get(7).grid[0] ="                  ";chunks.get(16).get(8).grid[0] ="                  ";chunks.get(16).get(9).grid[0] ="                  ";chunks.get(16).get(10).grid[0] ="                  ";
		chunks.get(16).get(0).grid[1]="                  ";chunks.get(16).get(1).grid[1]="                  ";chunks.get(16).get(2).grid[1] ="                  ";chunks.get(16).get(3).grid[1] ="                  ";chunks.get(16).get(4).grid[1] ="                  ";chunks.get(16).get(5).grid[1] ="                  ";chunks.get(16).get(6).grid[1] ="                  ";chunks.get(16).get(7).grid[1] ="                  ";chunks.get(16).get(8).grid[1] ="                  ";chunks.get(16).get(9).grid[1] ="                  ";chunks.get(16).get(10).grid[1] ="                  ";
		chunks.get(16).get(0).grid[2]="                  ";chunks.get(16).get(1).grid[2]="                  ";chunks.get(16).get(2).grid[2] ="                  ";chunks.get(16).get(3).grid[2] ="                  ";chunks.get(16).get(4).grid[2] ="                  ";chunks.get(16).get(5).grid[2] ="                  ";chunks.get(16).get(6).grid[2] ="                  ";chunks.get(16).get(7).grid[2] ="                  ";chunks.get(16).get(8).grid[2] ="                  ";chunks.get(16).get(9).grid[2] ="                  ";chunks.get(16).get(10).grid[2] ="                  ";
		chunks.get(16).get(0).grid[3]="                  ";chunks.get(16).get(1).grid[3]="                  ";chunks.get(16).get(2).grid[3] ="                  ";chunks.get(16).get(3).grid[3] ="                  ";chunks.get(16).get(4).grid[3] ="                  ";chunks.get(16).get(5).grid[3] ="                  ";chunks.get(16).get(6).grid[3] ="                  ";chunks.get(16).get(7).grid[3] ="                  ";chunks.get(16).get(8).grid[3] ="                  ";chunks.get(16).get(9).grid[3] ="                  ";chunks.get(16).get(10).grid[3] ="                  ";
		chunks.get(16).get(0).grid[4]="                  ";chunks.get(16).get(1).grid[4]="                  ";chunks.get(16).get(2).grid[4] ="                  ";chunks.get(16).get(3).grid[4] ="                  ";chunks.get(16).get(4).grid[4] ="                  ";chunks.get(16).get(5).grid[4] ="                  ";chunks.get(16).get(6).grid[4] ="                  ";chunks.get(16).get(7).grid[4] ="                  ";chunks.get(16).get(8).grid[4] ="                  ";chunks.get(16).get(9).grid[4] ="                  ";chunks.get(16).get(10).grid[4] ="                  ";
		
		chunks.get(17).get(0).grid[0]="                  ";chunks.get(17).get(1).grid[0]="                  ";chunks.get(17).get(2).grid[0] ="                  ";chunks.get(17).get(3).grid[0] ="                  ";chunks.get(17).get(4).grid[0] ="                  ";chunks.get(17).get(5).grid[0] ="                  ";chunks.get(17).get(6).grid[0] ="                  ";chunks.get(17).get(7).grid[0] ="                  ";chunks.get(17).get(8).grid[0] ="                  ";chunks.get(17).get(9).grid[0] ="                  ";chunks.get(17).get(10).grid[0] ="                  ";
		chunks.get(17).get(0).grid[1]="                  ";chunks.get(17).get(1).grid[1]="                  ";chunks.get(17).get(2).grid[1] ="                  ";chunks.get(17).get(3).grid[1] ="                  ";chunks.get(17).get(4).grid[1] ="                  ";chunks.get(17).get(5).grid[1] ="                  ";chunks.get(17).get(6).grid[1] ="                  ";chunks.get(17).get(7).grid[1] ="                  ";chunks.get(17).get(8).grid[1] ="                  ";chunks.get(17).get(9).grid[1] ="                  ";chunks.get(17).get(10).grid[1] ="                  ";
		chunks.get(17).get(0).grid[2]="                  ";chunks.get(17).get(1).grid[2]="                  ";chunks.get(17).get(2).grid[2] ="                  ";chunks.get(17).get(3).grid[2] ="                  ";chunks.get(17).get(4).grid[2] ="                  ";chunks.get(17).get(5).grid[2] ="                  ";chunks.get(17).get(6).grid[2] ="                  ";chunks.get(17).get(7).grid[2] ="                  ";chunks.get(17).get(8).grid[2] ="                  ";chunks.get(17).get(9).grid[2] ="                  ";chunks.get(17).get(10).grid[2] ="                  ";
		chunks.get(17).get(0).grid[3]="                  ";chunks.get(17).get(1).grid[3]="                  ";chunks.get(17).get(2).grid[3] ="                  ";chunks.get(17).get(3).grid[3] ="                  ";chunks.get(17).get(4).grid[3] ="                  ";chunks.get(17).get(5).grid[3] ="                  ";chunks.get(17).get(6).grid[3] ="                  ";chunks.get(17).get(7).grid[3] ="                  ";chunks.get(17).get(8).grid[3] ="                  ";chunks.get(17).get(9).grid[3] ="                  ";chunks.get(17).get(10).grid[3] ="                  ";
		chunks.get(17).get(0).grid[4]="                  ";chunks.get(17).get(1).grid[4]="                  ";chunks.get(17).get(2).grid[4] ="                  ";chunks.get(17).get(3).grid[4] ="                  ";chunks.get(17).get(4).grid[4] ="                  ";chunks.get(17).get(5).grid[4] ="                  ";chunks.get(17).get(6).grid[4] ="                  ";chunks.get(17).get(7).grid[4] ="                  ";chunks.get(17).get(8).grid[4] ="                  ";chunks.get(17).get(9).grid[4] ="                  ";chunks.get(17).get(10).grid[4] ="                  ";
	
		chunks.get(18).get(0).grid[0]="                  ";chunks.get(18).get(1).grid[0]="                  ";chunks.get(18).get(2).grid[0] ="                  ";chunks.get(18).get(3).grid[0] ="                  ";chunks.get(18).get(4).grid[0] ="                  ";chunks.get(18).get(5).grid[0] ="                  ";chunks.get(18).get(6).grid[0] ="                  ";chunks.get(18).get(7).grid[0] ="                  ";chunks.get(18).get(8).grid[0] ="                  ";chunks.get(18).get(9).grid[0] ="                  ";chunks.get(18).get(10).grid[0] ="                  ";
		chunks.get(18).get(0).grid[1]="                  ";chunks.get(18).get(1).grid[1]="                  ";chunks.get(18).get(2).grid[1] ="                  ";chunks.get(18).get(3).grid[1] ="                  ";chunks.get(18).get(4).grid[1] ="                  ";chunks.get(18).get(5).grid[1] ="                  ";chunks.get(18).get(6).grid[1] ="                  ";chunks.get(18).get(7).grid[1] ="                  ";chunks.get(18).get(8).grid[1] ="                  ";chunks.get(18).get(9).grid[1] ="                  ";chunks.get(18).get(10).grid[1] ="                  ";
		chunks.get(18).get(0).grid[2]="                  ";chunks.get(18).get(1).grid[2]="                  ";chunks.get(18).get(2).grid[2] ="                  ";chunks.get(18).get(3).grid[2] ="                  ";chunks.get(18).get(4).grid[2] ="                  ";chunks.get(18).get(5).grid[2] ="                  ";chunks.get(18).get(6).grid[2] ="                  ";chunks.get(18).get(7).grid[2] ="                  ";chunks.get(18).get(8).grid[2] ="                  ";chunks.get(18).get(9).grid[2] ="                  ";chunks.get(18).get(10).grid[2] ="                  ";
		chunks.get(18).get(0).grid[3]="                  ";chunks.get(18).get(1).grid[3]="                  ";chunks.get(18).get(2).grid[3] ="                  ";chunks.get(18).get(3).grid[3] ="                  ";chunks.get(18).get(4).grid[3] ="                  ";chunks.get(18).get(5).grid[3] ="                  ";chunks.get(18).get(6).grid[3] ="                  ";chunks.get(18).get(7).grid[3] ="                  ";chunks.get(18).get(8).grid[3] ="                  ";chunks.get(18).get(9).grid[3] ="                  ";chunks.get(18).get(10).grid[3] ="                  ";
		chunks.get(18).get(0).grid[4]="                  ";chunks.get(18).get(1).grid[4]="                  ";chunks.get(18).get(2).grid[4] ="                  ";chunks.get(18).get(3).grid[4] ="                  ";chunks.get(18).get(4).grid[4] ="                  ";chunks.get(18).get(5).grid[4] ="                  ";chunks.get(18).get(6).grid[4] ="                  ";chunks.get(18).get(7).grid[4] ="                  ";chunks.get(18).get(8).grid[4] ="                  ";chunks.get(18).get(9).grid[4] ="                  ";chunks.get(18).get(10).grid[4] ="                  ";

		chunks.get(19).get(0).grid[0]="                  ";chunks.get(19).get(1).grid[0]="                  ";chunks.get(19).get(2).grid[0] ="                  ";chunks.get(19).get(3).grid[0] ="                  ";chunks.get(19).get(4).grid[0] ="                  ";chunks.get(19).get(5).grid[0] ="                  ";chunks.get(19).get(6).grid[0] ="                  ";chunks.get(19).get(7).grid[0] ="                  ";chunks.get(19).get(8).grid[0] ="                  ";chunks.get(19).get(9).grid[0] ="                  ";chunks.get(19).get(10).grid[0] ="                  ";
		chunks.get(19).get(0).grid[1]="                  ";chunks.get(19).get(1).grid[1]="                  ";chunks.get(19).get(2).grid[1] ="                  ";chunks.get(19).get(3).grid[1] ="                  ";chunks.get(19).get(4).grid[1] ="                  ";chunks.get(19).get(5).grid[1] ="                  ";chunks.get(19).get(6).grid[1] ="                  ";chunks.get(19).get(7).grid[1] ="                  ";chunks.get(19).get(8).grid[1] ="                  ";chunks.get(19).get(9).grid[1] ="                  ";chunks.get(19).get(10).grid[1] ="                  ";
		chunks.get(19).get(0).grid[2]="                  ";chunks.get(19).get(1).grid[2]="                  ";chunks.get(19).get(2).grid[2] ="                  ";chunks.get(19).get(3).grid[2] ="                  ";chunks.get(19).get(4).grid[2] ="                  ";chunks.get(19).get(5).grid[2] ="                  ";chunks.get(19).get(6).grid[2] ="                  ";chunks.get(19).get(7).grid[2] ="                  ";chunks.get(19).get(8).grid[2] ="                  ";chunks.get(19).get(9).grid[2] ="                  ";chunks.get(19).get(10).grid[2] ="                  ";
		chunks.get(19).get(0).grid[3]="                  ";chunks.get(19).get(1).grid[3]="                  ";chunks.get(19).get(2).grid[3] ="                  ";chunks.get(19).get(3).grid[3] ="                  ";chunks.get(19).get(4).grid[3] ="                  ";chunks.get(19).get(5).grid[3] ="                  ";chunks.get(19).get(6).grid[3] ="                  ";chunks.get(19).get(7).grid[3] ="                  ";chunks.get(19).get(8).grid[3] ="                  ";chunks.get(19).get(9).grid[3] ="                  ";chunks.get(19).get(10).grid[3] ="                  ";
		chunks.get(19).get(0).grid[4]="                  ";chunks.get(19).get(1).grid[4]="                  ";chunks.get(19).get(2).grid[4] ="                  ";chunks.get(19).get(3).grid[4] ="                  ";chunks.get(19).get(4).grid[4] ="                  ";chunks.get(19).get(5).grid[4] ="                  ";chunks.get(19).get(6).grid[4] ="                  ";chunks.get(19).get(7).grid[4] ="                  ";chunks.get(19).get(8).grid[4] ="                  ";chunks.get(19).get(9).grid[4] ="                  ";chunks.get(19).get(10).grid[4] ="                  ";


		chunks.get(20).get(0).grid[0]="                  ";chunks.get(20).get(1).grid[0]="                  ";chunks.get(20).get(2).grid[0] ="                  ";chunks.get(20).get(3).grid[0] ="                  ";chunks.get(20).get(4).grid[0] ="                  ";chunks.get(20).get(5).grid[0] ="                  ";chunks.get(20).get(6).grid[0] ="                  ";chunks.get(20).get(7).grid[0] ="                  ";chunks.get(20).get(8).grid[0] ="                  ";chunks.get(20).get(9).grid[0] ="                  ";chunks.get(20).get(10).grid[0] ="                  ";
		chunks.get(20).get(0).grid[1]="                  ";chunks.get(20).get(1).grid[1]="                  ";chunks.get(20).get(2).grid[1] ="                  ";chunks.get(20).get(3).grid[1] ="                  ";chunks.get(20).get(4).grid[1] ="                  ";chunks.get(20).get(5).grid[1] ="                  ";chunks.get(20).get(6).grid[1] ="                  ";chunks.get(20).get(7).grid[1] ="                  ";chunks.get(20).get(8).grid[1] ="                  ";chunks.get(20).get(9).grid[1] ="                  ";chunks.get(20).get(10).grid[1] ="                  ";
		chunks.get(20).get(0).grid[2]="                  ";chunks.get(20).get(1).grid[2]="                  ";chunks.get(20).get(2).grid[2] ="                  ";chunks.get(20).get(3).grid[2] ="                  ";chunks.get(20).get(4).grid[2] ="                  ";chunks.get(20).get(5).grid[2] ="                  ";chunks.get(20).get(6).grid[2] ="                  ";chunks.get(20).get(7).grid[2] ="                  ";chunks.get(20).get(8).grid[2] ="                  ";chunks.get(20).get(9).grid[2] ="                  ";chunks.get(20).get(10).grid[2] ="                  ";
		chunks.get(20).get(0).grid[3]="                  ";chunks.get(20).get(1).grid[3]="                  ";chunks.get(20).get(2).grid[3] ="                  ";chunks.get(20).get(3).grid[3] ="                  ";chunks.get(20).get(4).grid[3] ="                  ";chunks.get(20).get(5).grid[3] ="                  ";chunks.get(20).get(6).grid[3] ="                  ";chunks.get(20).get(7).grid[3] ="                  ";chunks.get(20).get(8).grid[3] ="                  ";chunks.get(20).get(9).grid[3] ="                  ";chunks.get(20).get(10).grid[3] ="                  ";
		chunks.get(20).get(0).grid[4]="                  ";chunks.get(20).get(1).grid[4]="                  ";chunks.get(20).get(2).grid[4] ="                  ";chunks.get(20).get(3).grid[4] ="                  ";chunks.get(20).get(4).grid[4] ="                  ";chunks.get(20).get(5).grid[4] ="                  ";chunks.get(20).get(6).grid[4] ="                  ";chunks.get(20).get(7).grid[4] ="                  ";chunks.get(20).get(8).grid[4] ="                  ";chunks.get(20).get(9).grid[4] ="                  ";chunks.get(20).get(10).grid[4] ="                  ";

		chunks.get(21).get(0).grid[0]="                  ";chunks.get(21).get(1).grid[0]="                  ";chunks.get(21).get(2).grid[0] ="                  ";chunks.get(21).get(3).grid[0] ="                  ";chunks.get(21).get(4).grid[0] ="                  ";chunks.get(21).get(5).grid[0] ="                  ";chunks.get(21).get(6).grid[0] ="                  ";chunks.get(21).get(7).grid[0] ="                  ";chunks.get(21).get(8).grid[0] ="                  ";chunks.get(21).get(9).grid[0] ="                  ";chunks.get(21).get(10).grid[0] ="                  ";
		chunks.get(21).get(0).grid[1]="                  ";chunks.get(21).get(1).grid[1]="                  ";chunks.get(21).get(2).grid[1] ="                  ";chunks.get(21).get(3).grid[1] ="                  ";chunks.get(21).get(4).grid[1] ="                  ";chunks.get(21).get(5).grid[1] ="                  ";chunks.get(21).get(6).grid[1] ="                  ";chunks.get(21).get(7).grid[1] ="                  ";chunks.get(21).get(8).grid[1] ="                  ";chunks.get(21).get(9).grid[1] ="                  ";chunks.get(21).get(10).grid[1] ="                  ";
		chunks.get(21).get(0).grid[2]="                  ";chunks.get(21).get(1).grid[2]="                  ";chunks.get(21).get(2).grid[2] ="                  ";chunks.get(21).get(3).grid[2] ="                  ";chunks.get(21).get(4).grid[2] ="                  ";chunks.get(21).get(5).grid[2] ="                  ";chunks.get(21).get(6).grid[2] ="                  ";chunks.get(21).get(7).grid[2] ="                  ";chunks.get(21).get(8).grid[2] ="                  ";chunks.get(21).get(9).grid[2] ="                  ";chunks.get(21).get(10).grid[2] ="                  ";
		chunks.get(21).get(0).grid[3]="                  ";chunks.get(21).get(1).grid[3]="                  ";chunks.get(21).get(2).grid[3] ="                  ";chunks.get(21).get(3).grid[3] ="                  ";chunks.get(21).get(4).grid[3] ="                  ";chunks.get(21).get(5).grid[3] ="                  ";chunks.get(21).get(6).grid[3] ="                  ";chunks.get(21).get(7).grid[3] ="                  ";chunks.get(21).get(8).grid[3] ="                  ";chunks.get(21).get(9).grid[3] ="                  ";chunks.get(21).get(10).grid[3] ="                  ";
		chunks.get(21).get(0).grid[4]="                  ";chunks.get(21).get(1).grid[4]="                  ";chunks.get(21).get(2).grid[4] ="                  ";chunks.get(21).get(3).grid[4] ="                  ";chunks.get(21).get(4).grid[4] ="                  ";chunks.get(21).get(5).grid[4] ="                  ";chunks.get(21).get(6).grid[4] ="                  ";chunks.get(21).get(7).grid[4] ="                  ";chunks.get(21).get(8).grid[4] ="                  ";chunks.get(21).get(9).grid[4] ="                  ";chunks.get(21).get(10).grid[4] ="                  ";

		chunks.get(22).get(0).grid[0]="                  ";chunks.get(22).get(1).grid[0]="                  ";chunks.get(22).get(2).grid[0] ="                  ";chunks.get(22).get(3).grid[0] ="                  ";chunks.get(22).get(4).grid[0] ="                  ";chunks.get(22).get(5).grid[0] ="                  ";chunks.get(22).get(6).grid[0] ="                  ";chunks.get(22).get(7).grid[0] ="                  ";chunks.get(22).get(8).grid[0] ="                  ";chunks.get(22).get(9).grid[0] ="                  ";chunks.get(22).get(10).grid[0] ="                  ";
		chunks.get(22).get(0).grid[1]="                  ";chunks.get(22).get(1).grid[1]="                  ";chunks.get(22).get(2).grid[1] ="                  ";chunks.get(22).get(3).grid[1] ="                  ";chunks.get(22).get(4).grid[1] ="                  ";chunks.get(22).get(5).grid[1] ="                  ";chunks.get(22).get(6).grid[1] ="                  ";chunks.get(22).get(7).grid[1] ="                  ";chunks.get(22).get(8).grid[1] ="                  ";chunks.get(22).get(9).grid[1] ="                  ";chunks.get(22).get(10).grid[1] ="                  ";
		chunks.get(22).get(0).grid[2]="                  ";chunks.get(22).get(1).grid[2]="                  ";chunks.get(22).get(2).grid[2] ="                  ";chunks.get(22).get(3).grid[2] ="                  ";chunks.get(22).get(4).grid[2] ="                  ";chunks.get(22).get(5).grid[2] ="                  ";chunks.get(22).get(6).grid[2] ="                  ";chunks.get(22).get(7).grid[2] ="                  ";chunks.get(22).get(8).grid[2] ="                  ";chunks.get(22).get(9).grid[2] ="                  ";chunks.get(22).get(10).grid[2] ="                  ";
		chunks.get(22).get(0).grid[3]="                  ";chunks.get(22).get(1).grid[3]="                  ";chunks.get(22).get(2).grid[3] ="                  ";chunks.get(22).get(3).grid[3] ="                  ";chunks.get(22).get(4).grid[3] ="                  ";chunks.get(22).get(5).grid[3] ="                  ";chunks.get(22).get(6).grid[3] ="                  ";chunks.get(22).get(7).grid[3] ="                  ";chunks.get(22).get(8).grid[3] ="                  ";chunks.get(22).get(9).grid[3] ="                  ";chunks.get(22).get(10).grid[3] ="                  ";
		chunks.get(22).get(0).grid[4]="                  ";chunks.get(22).get(1).grid[4]="                  ";chunks.get(22).get(2).grid[4] ="                  ";chunks.get(22).get(3).grid[4] ="                  ";chunks.get(22).get(4).grid[4] ="                  ";chunks.get(22).get(5).grid[4] ="                  ";chunks.get(22).get(6).grid[4] ="                  ";chunks.get(22).get(7).grid[4] ="                  ";chunks.get(22).get(8).grid[4] ="                  ";chunks.get(22).get(9).grid[4] ="                  ";chunks.get(22).get(10).grid[4] ="                  ";
		
		chunks.get(23).get(0).grid[0]="                  ";chunks.get(23).get(1).grid[0]="                  ";chunks.get(23).get(2).grid[0] ="                  ";chunks.get(23).get(3).grid[0] ="                  ";chunks.get(23).get(4).grid[0] ="                  ";chunks.get(23).get(5).grid[0] ="                  ";chunks.get(23).get(6).grid[0] ="                  ";chunks.get(23).get(7).grid[0] ="                  ";chunks.get(23).get(8).grid[0] ="                  ";chunks.get(23).get(9).grid[0] ="                  ";chunks.get(23).get(10).grid[0] ="                  ";
		chunks.get(23).get(0).grid[1]="                  ";chunks.get(23).get(1).grid[1]="                  ";chunks.get(23).get(2).grid[1] ="                  ";chunks.get(23).get(3).grid[1] ="                  ";chunks.get(23).get(4).grid[1] ="                  ";chunks.get(23).get(5).grid[1] ="                  ";chunks.get(23).get(6).grid[1] ="                  ";chunks.get(23).get(7).grid[1] ="                  ";chunks.get(23).get(8).grid[1] ="                  ";chunks.get(23).get(9).grid[1] ="                  ";chunks.get(23).get(10).grid[1] ="                  ";
		chunks.get(23).get(0).grid[2]="                  ";chunks.get(23).get(1).grid[2]="                  ";chunks.get(23).get(2).grid[2] ="                  ";chunks.get(23).get(3).grid[2] ="                  ";chunks.get(23).get(4).grid[2] ="                  ";chunks.get(23).get(5).grid[2] ="                  ";chunks.get(23).get(6).grid[2] ="                  ";chunks.get(23).get(7).grid[2] ="                  ";chunks.get(23).get(8).grid[2] ="                  ";chunks.get(23).get(9).grid[2] ="                  ";chunks.get(23).get(10).grid[2] ="                  ";
		chunks.get(23).get(0).grid[3]="                  ";chunks.get(23).get(1).grid[3]="                  ";chunks.get(23).get(2).grid[3] ="                  ";chunks.get(23).get(3).grid[3] ="                  ";chunks.get(23).get(4).grid[3] ="                  ";chunks.get(23).get(5).grid[3] ="                  ";chunks.get(23).get(6).grid[3] ="                  ";chunks.get(23).get(7).grid[3] ="                  ";chunks.get(23).get(8).grid[3] ="                  ";chunks.get(23).get(9).grid[3] ="                  ";chunks.get(23).get(10).grid[3] ="                  ";
		chunks.get(23).get(0).grid[4]="                  ";chunks.get(23).get(1).grid[4]="                  ";chunks.get(23).get(2).grid[4] ="                  ";chunks.get(23).get(3).grid[4] ="                  ";chunks.get(23).get(4).grid[4] ="                  ";chunks.get(23).get(5).grid[4] ="                  ";chunks.get(23).get(6).grid[4] ="                  ";chunks.get(23).get(7).grid[4] ="                  ";chunks.get(23).get(8).grid[4] ="                  ";chunks.get(23).get(9).grid[4] ="                  ";chunks.get(23).get(10).grid[4] ="                  ";
		
 */












